workspace:
  base: /go/src
  path: github.com/appleboy/drone-line

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: appleboy/golang-testing:1.9
    group: testing
    commands:
      - make vet
      - make lint
      - make test-vendor
      - make misspell-check

  test:
    image: appleboy/golang-testing:1.9
    group: testing
    secrets: [ line_to, line_channel_secret, line_channel_token ]
    commands:
      - make test
      - make coverage

  build:
    image: appleboy/golang-testing:1.9
    group: testing
    commands:
      - make static_build

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.txt
    when:
      event: [ push, pull_request ]

  release:
    image: appleboy/golang-testing:1.9
    commands:
      - make release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  facebook:
    image: appleboy/drone-facebook
    secrets: [ fb_page_token, fb_verify_token ]
    pull: true
    to: 1234973386524610
    when:
      status: [ changed, failure ]
